# Generated by Django 4.0.6 on 2022-07-31 20:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
