# Generated by Django 4.0.6 on 2022-08-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0002_person_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='descripcion',
            new_name='description',
        ),
    ]
